apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: project
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: api-rest
  name: api-rest
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-rest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-rest
    spec:
      containers:
      - image: sergioarmgpl/wasm-rust-api
        name: wasm-rust-api
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: api-rest
  name: api-rest-svc
  namespace: project
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-rest
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-rest-ingress
  namespace: project
spec:
  ingressClassName: nginx
  rules:
    - host: <REPLACE_WITH_YOUR_LB_IP_ADDRESS>.nip.io
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: api-rest-svc
                port:
                  number: 8080
            path: /